/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "secondary-fixed-dim": "#e9c176",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f3f0ec",
        "tertiary-container": "#26211b",
        "surface-container-low": "#f6f3ef",
        "on-tertiary-fixed-variant": "#4c463e",
        "on-tertiary-container": "#90887f",
        "inverse-primary": "#dac1bc",
        "on-primary-container": "#998480",
        "outline": "#817472",
        "on-secondary-fixed-variant": "#5d4201",
        "on-surface": "#1c1c19",
        "primary-container": "#2c1e1b",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-surface-variant": "#4f4442",
        "secondary": "#775a19",
        "surface": "#fcf9f5",
        "inverse-surface": "#31302e",
        "on-primary": "#ffffff",
        "secondary-container": "#fed488",
        "on-error": "#ffffff",
        "primary-fixed": "#f7ddd8",
        "surface-tint": "#6d5a56",
        "primary": "#130806",
        "on-primary-fixed": "#261815",
        "on-primary-fixed-variant": "#54433f",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#dac1bc",
        "surface-dim": "#dcdad6",
        "tertiary": "#0f0b06",
        "outline-variant": "#d2c3c0",
        "error-container": "#ffdad6",
        "surface-container": "#f0ede9",
        "tertiary-fixed": "#ebe1d6",
        "background": "#fcf9f5",
        "on-secondary-container": "#785a1a",
        "on-tertiary-fixed": "#201b15",
        "on-secondary-fixed": "#261900",
        "secondary-fixed": "#ffdea5",
        "surface-bright": "#fcf9f5",
        "tertiary-fixed-dim": "#cfc5bb",
        "on-background": "#1c1c19",
        "surface-container-highest": "#e5e2de",
        "surface-container-high": "#ebe8e4",
        "surface-variant": "#e5e2de",
        "silk-base": "#FDFBF7",
        "ganache-rich": "#2D1B14",
        "copper-accent": "#C19A6B",
        "porcelain-surface": "#FFFFFF",
        "pistachio-light": "#E8F0E6",
        "vanilla-cream": "#F9F5F0"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "gutter": "24px",
        "unit": "4px",
        "section-gap": "120px",
        "margin-page": "64px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px"
      },
      "fontFamily": {
        "headline-md": ["Noto Serif"],
        "label-sm": ["Manrope"],
        "headline-lg": ["Noto Serif"],
        "body-lg": ["Manrope"],
        "display-xl": ["Noto Serif"],
        "body-md": ["Manrope"]
      },
      "fontSize": {
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-2xl": ["120px", { lineHeight: "1", letterSpacing: "-0.04em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
